import { mkdir, readdir, rm, writeFile } from "node:fs/promises"
import { join, relative, sep } from "node:path"
import { fileURLToPath } from "node:url"

import { compileMap } from "./compile.ts"
import type { CompiledMap, MapId, ReleaseLock } from "./format.ts"
import { checkPermanence, lockFor } from "./permanence.ts"
import { toSummary } from "./reader.ts"
import {
  listLockedMaps,
  listSourceMaps,
  lockFileName,
  readLock,
  readMapSources,
} from "./sources.ts"

/** Where the build reads and writes. */
export interface BuildOptions {
  /** Holds `methods.yaml` and `maps/<map>/`. */
  sourcesDir: string
  /** Receives `<map>.json` and `registry.ts`. Its old JSON files are removed. */
  outDir: string
  /** Holds the release locks, `<map>.lock.json`. */
  releasedDir: string
  /**
   * `frozen` never writes a lock and stops when a lock is out of date (CI and
   * every build). `lock` writes the lock of each Map that has one, and of
   * each Map in `maps` (which creates a lock at launch).
   */
  mode: "frozen" | "lock"
  /** In `lock` mode, Maps to lock even though they have no lock yet. */
  maps?: MapId[]
}

/**
 * Compiles every Map under `sourcesDir`, runs the permanence check, and
 * writes the output. Returns the problems that stopped it; when there are
 * any, nothing is written.
 */
export async function buildMaps(options: BuildOptions): Promise<string[]> {
  const { sourcesDir, releasedDir, mode } = options
  const problems: string[] = []
  const compiled: CompiledMap[] = []
  const locks = new Map<MapId, ReleaseLock | undefined>()
  const sourceMaps = await listSourceMaps(sourcesDir)

  for (const dir of sourceMaps) {
    const sources = await readMapSources(sourcesDir, dir)

    if (!sources.ok) {
      problems.push(...sources.problems)
      continue
    }

    if (sources.value.map.id !== dir) {
      problems.push(
        `maps/${dir}/map.yaml: the Map id "${sources.value.map.id}" must match its directory "${dir}"`
      )
      continue
    }

    const result = compileMap(sources.value)

    if (!result.ok) {
      problems.push(...result.problems.map((p) => `${dir}: ${p}`))
      continue
    }

    const lock = await readLock(releasedDir, dir)

    if (!lock.ok) {
      problems.push(...lock.problems)
      continue
    }

    problems.push(
      ...checkPermanence(result.map, lock.value, { frozen: mode === "frozen" })
    )
    compiled.push(result.map)
    locks.set(dir, lock.value)
  }

  for (const map of await listLockedMaps(releasedDir)) {
    if (!sourceMaps.includes(map)) {
      problems.push(
        `Released Map "${map}" has no sources. A released Map is permanent: restore maps/${map}/.`
      )
    }
  }

  for (const map of options.maps ?? []) {
    if (!sourceMaps.includes(map)) problems.push(`No Map "${map}" to lock`)
  }

  if (problems.length > 0) return problems

  await writeOutput(options.outDir, compiled)

  if (mode === "lock") {
    await writeLocks(
      releasedDir,
      nextLocks(compiled, locks, options.maps ?? [])
    )
  }

  return []
}

async function writeOutput(outDir: string, maps: CompiledMap[]) {
  await mkdir(outDir, { recursive: true })

  for (const file of await readdir(outDir)) {
    if (file.endsWith(".json")) await rm(join(outDir, file))
  }

  for (const map of maps) {
    await writeFile(join(outDir, `${map.id}.json`), JSON.stringify(map))
  }

  await writeFile(join(outDir, "registry.ts"), registrySource(outDir, maps))
}

/** The lock of each Map that has one, and of each named Map. */
function nextLocks(
  maps: CompiledMap[],
  previous: Map<MapId, ReleaseLock | undefined>,
  named: MapId[]
): ReleaseLock[] {
  return maps
    .filter((map) => previous.get(map.id) || named.includes(map.id))
    .map((map) => lockFor(map, previous.get(map.id)))
}

async function writeLocks(releasedDir: string, locks: ReleaseLock[]) {
  await mkdir(releasedDir, { recursive: true })

  for (const lock of locks) {
    await writeFile(
      join(releasedDir, lockFileName(lock.map)),
      `${JSON.stringify(lock, null, 2)}\n`
    )
  }
}

/**
 * The generated registry module. One static `import()` per Map lets a
 * bundler split each Map into its own chunk.
 */
function registrySource(outDir: string, maps: CompiledMap[]): string {
  const srcDir = relative(outDir, fileURLToPath(new URL(".", import.meta.url)))
    .split(sep)
    .join("/")
  const catalog = maps.map(toSummary)
  const loaders = maps.map(
    (map) =>
      `    ${JSON.stringify(map.id)}: () =>\n      import(${JSON.stringify(`./${map.id}.json`)}, { with: { type: "json" } }).then(asMap),`
  )

  return [
    "// Generated by @workspace/game-data's build. Do not edit.",
    `import type { CompiledMap } from "${srcDir}/format.ts"`,
    `import type { MapRegistry } from "${srcDir}/reader.ts"`,
    "",
    "const asMap = (module: { default: unknown }) => module.default as CompiledMap",
    "",
    "export const registry: MapRegistry = {",
    `  catalog: ${JSON.stringify(catalog)},`,
    "  load: {",
    ...loaders,
    "  },",
    "}",
    "",
  ].join("\n")
}
